### ISSUE TITLE
regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by canguruhh** [trezor/trezor.js#48]
When I try to require trezor.js i get the following error message:
```
trezor/node_modules/trezor.js-node/lib/device.js:297
            var _ref = _asyncToGenerator( /*#__PURE__*/regeneratorRuntime.mark(function _callee(session) {
                                                       ^

ReferenceError: regeneratorRuntime is not defined
    at .../trezor/node_modules/trezor.js-node/lib/device.js:297:56
    at .../trezor/node_modules/trezor.js-node/lib/device.js:341:10
    at Object.<anonymous> (.../trezor/node_modules/trezor.js-node/lib/device.js:780:2)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Module.require (module.js:593:17)
    at require (internal/module.js:11:18)
```
i just used npm install trezor.js

**Comment by idimon4uk** [comment]
I have the same problem ! Does anyone can help ?

**Comment by SoYouDie** [comment]
The same. Any solutions?

**Comment by karel-3d** [comment]
It was something with babel

I wanted to fix this but there were some problems that I forgot now, and I don't currently have time for this. As a temporary measure, please incude babel-polyfill in your project.

**Comment by SoYouDie** [comment]
https://stackoverflow.com/a/33527883 this answer help me.

**Comment by wbobeirne** [comment]
I don't think this fix works when using `trezor.js` in a Node (e.g. Electron) environment. Unfortunately this is kind of a hard stop on Trezor integration.

**Comment by karel-3d** [comment]
Fixed
