### ISSUE TITLE
Unable to connect to bridge on 21325

### ISSUE THREAD

**Issue by patwhite** [trezor/trezor.js#59]
I just updated to the newest version of trezord and it appears to be running on port 21325. However, the trezor.js library appears to be trying to contact port 21324. I don't see an easy way of changing that from the api documentation, nor why exactly the ports changed.  To be clear, I can successfully browse to localhost:21325 and see the attached device.

See the attached error message:

```[trezor-link] Calling FallbackTransport.init( true )
[trezor-link] Calling BridgeTransport.init( true )
[trezor-link] Error in BridgeTransport.init Error
    at _callee$ (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/trezor-link/lib/bridge/http.js:62:19)
    at tryCatch (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/regenerator-runtime/runtime.js:65:40)
    at Generator.invoke [as _invoke] (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/regenerator-runtime/runtime.js:303:22)
    at Generator.prototype.(anonymous function) [as next] (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/regenerator-runtime/runtime.js:117:21)
    at step (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/trezor-link/lib/bridge/http.js:79:191)
    at /Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/trezor-link/lib/bridge/http.js:79:361
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
[trezor-link] Calling BridgeTransport.init( true )
[trezor-link] Error in BridgeTransport.init { FetchError: request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324
    at ClientRequest.<anonymous> (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
[trezor-link] Error in FallbackTransport.init { FetchError: request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324
    at ClientRequest.<anonymous> (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }
List error: { FetchError: request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324
    at ClientRequest.<anonymous> (/Users/patwhite/Source/bitalpha/trezor-test-2/node_modules/node-fetch/index.js:133:11)
    at emitOne (events.js:115:13)
    at ClientRequest.emit (events.js:210:7)
    at TLSSocket.socketErrorListener (_http_client.js:401:9)
    at emitOne (events.js:115:13)
    at TLSSocket.emit (events.js:210:7)
    at emitErrorNT (internal/streams/destroy.js:64:8)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
  name: 'FetchError',
  message: 'request to https://localback.net:21324 failed, reason: connect ECONNREFUSED 127.0.0.1:21324',
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED' }```

**Comment by prusnak** [comment]
You most probably don't want to use trezor.js directly anyway. The proper way how to interact with TREZOR from your website is via https://github.com/trezor/connect

**Comment by patwhite** [comment]
I'm not doing this through a website, as said above, I'm doing this through node (with the goal of using this embedded in an electron app). Either way, I think it's noteworthy that this doesn't work as described, and there's not documentation on how to change ports to make this work.

**Comment by prusnak** [comment]
OK, reopening. @karel-3d might want to have a look?

**Comment by karel-3d** [comment]
try newest one, the URL spoofing might have helped

**Comment by albertogiovanelli** [comment]
@patwhite Did you connect your trezor using trezor.js inside node at the end?Because I'm getting the same error now with latest versions of trezor bridge and trezor.js. Thanks!
